openapi: 3.0.0
info:
  description: Film Service
  version: '0.1'
  title: Film Service

tags:
  - name: film-controller
    description: Film Controller

paths:
  /api/film:
    get:
      operationId: getFilmsByCriteria
      tags:
        - film-controller
      summary: Get films list
      parameters:
        - name: criteria
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/FilmCriteria'
      responses:
        200:
          description: List of films
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilmList'
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

    post:
      operationId: createFilm
      tags:
        - film-controller
      summary: Create a new film
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertFilm'
      responses:
        200:
          description: Id of the created film
          content:
            application/json:
              schema:
                type: integer
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/film/{filmId}:
    parameters:
      - $ref: '#/components/parameters/FilmId'

    get:
      operationId: getFilm
      tags:
        - film-controller
      summary: Get the film
      responses:
        200:
          description: Film by provided id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

    put:
      operationId: updateFilm
      tags:
        - film-controller
      summary: Update the film
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertFilm'
      responses:
        204:
          description: Film was updated successfully
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

    delete:
      operationId: deleteFilm
      tags:
        - film-controller
      summary: Delete the film
      responses:
        204:
          description: Film was deleted successfully
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

components:
  parameters:
    FilmId:
      name: filmId
      in: path
      required: true
      schema:
        type: integer

  schemas:
    UpsertFilm:
      type: object
      properties:
        title:
          type: string
          maxLength: 256
        description:
          type: string
          maxLength: 5000
      required:
        - title
        - description

    Film:
      allOf:
        - $ref: '#/components/schemas/UpsertFilm'
        - type: object
          properties:
            id:
              type: integer
            totalRating:
              $ref: 'film-rating-api.yaml#/components/schemas/FilmRating'
            currentUserRating:
              $ref: 'film-rating-api.yaml#/components/schemas/FilmRating'
          required:
            - id

    FilmList:
      allOf:
        - $ref: 'common-types.yaml#/components/schemas/BaseList'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Film'
          required:
            - items

    FilmCriteria:
      allOf:
        - $ref: 'common-types.yaml#/components/schemas/BaseCriteria'
        - type: object
          properties:
            query:
              type: string