openapi: 3.0.0
info:
  description: Test Service
  version: '1.0'
  title: Test Service

tags:
  - name: test-controller
    description: Test Controller
servers:
  - url: http://localhost:8080

paths:
  /api/test:
    get:
      operationId: test
      tags:
        - test-controller
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'