name: build-jar

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Package
      run: mvn -B package -DskipTests

    - uses: actions/upload-artifact@v4
      with:
        name: Rezflix-Backend
        path: ./target/rezflix.jar
